name: SFDX Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: install sfdx-cli and create security key file
      env:
        SERVER_KEY: ${{ secrets.SFDX_SERVER_KEY }}
      run: |
        npm install -g sfdx-cli
        echo "${SERVER_KEY}" > server.key
    - name: verify server key file
      run: echo "$(<server.key)"
    - name: authorize org
      env:
        CLIENT_ID: ${{ secrets.SFDEV_CLIENT_KEY }}
      run: |
        echo "CLIENT_ID=${CLIENT_ID}"
        sfdx force:auth:jwt:grant --clientid ${CLIENT_ID} -f ./server.key --username jdavidwestberry@gmail.com.cme.sfdev --instanceurl https://test.salesforce.com --setalias cme-uat --setdefaultdevhubusername
