name: SFDX Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: install sfdx-cli
      run: npm install -g sfdx-cli
    - name: check sfdx version
      run: sfdx --version