name: SFDX Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    -name: Use NPM to install SFDX CLI
     uses: actions/setup-node@v1
    -name: install sfdx-cli
     run: npm install -g sfdx-cli
    -name: sfdx version
     run: sfdx --version
