name: SFDX Test

on: [push]

jobs:
  sfdx_cli_job:
    runs-on: ubuntu-latest
    name: A job to setup SFDX CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./
      - name: SFDX action step
        id: sfdx_setup
        run: sfdx --version
