name: SFDX Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: install sfdx-cli and create security key file
      env:
        SERVER_KEY: ${{ secrets.SFDX_SERVER_KEY }}
      run: |
        npm install -g sfdx-cli
        echo "${SERVER_KEY}" > server.key
    - name: verify server key file
      run: echo "$(<server.key)"
#CLIENT_ID: 3MVG97wqanbUM37IrGKv0LG.6jUZzymv4_6CJULCoKNRWGUkXlAOv18C6tEitRkNV1DqkFjExPUybpJ0E7H0X