name: SFDEV build

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR branch target
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
      run: echo "$TARGET_BRANCH"